<?php
/**
 * @file
 * Create news content type and displays.
 */

/**
 * Implements hook_entity_info_alter().
 */
function ding_news_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['teaser_highlight'] = array(
    'label' => t('Teaser highlight'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_date_format_types().
 */
function ding_news_date_format_types() {
  return array(
    'ding_news_date_format' => t('Ding news date format'),
  );
}

/**
 * Implements hook_date_formats().
 *
 * Provides specific extra formats used by Ding! modules and assigning them
 * to specific date types.
 */
function ding_news_date_formats() {
  $formats = array();

  $formats[] = array(
    'type'    => 'ding_news_date_format',
    'format'  => 'd/m/Y',
    'locales' => array(),
  );

  // Save certain date formats into variables.
  foreach ($formats as $format) {
    variable_set('date_format_' . $format['type'], $format['format']);
  }

  return $formats;
}

include_once('ding_news.features.inc');

